export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCTS_DETAILS = "FETCH_PRODUCTS_DETAILS";
export const FETCH_PRODUCTS_DETAILS_SUCCESS = "FETCH_PRODUCTS_DETAILS_SUCCESS";
export const FETCH_PRODUCTS_DETAILS_ERROR = "FETCH_PRODUCTS_DETAILS_ERROR";

export const FETCH_PRODUCTS_REVIEWS = "FETCH_PRODUCTS_REVIEWS";
export const FETCH_PRODUCTS_REVIEWS_SUCCESS = "FETCH_PRODUCTS_REVIEWS_SUCCESS";
export const FETCH_PRODUCTS_REVIEWS_ERROR = "FETCH_PRODUCTS_REVIEWS_ERROR";

export const REGISTRATION = "REGISTRATION";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const AUTHORISATION = "AUTHORISATION";
export const AUTHORISATION_SUCCESS = "AUTHORISATION_SUCCESS";
export const AUTHORISATION_ERROR = "AUTHORISATION_ERROR";

export const SEND_COMMENT = "SEND_COMMENT";
export const SEND_COMMENT_SUCCESS = "SEND_COMMENT_SUCCESS";
export const SEND_COMMENT_ERROR = "SEND_COMMENT_ERROR";

export const LOGOUT = "LOGOUT";
